version: '3'
services:
  application:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    volumes:
      - ./src/application:/usr/src/app
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
