name: Upload Website

on:
  repository_dispatch:
    types: [build]
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - run: npm install --frozen-lockfile
      working-directory: './src/application'
    - run: npx cross-env CMS_ENDPOINT=${{ secrets.CMS_ENDPOINT}} CMS_API_KEY=${{ secrets.CMS_API_KEY}} next build
      working-directory: './src/application'
    - run: npm run export
      working-directory: './src/application'

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: './src/application/out'
